services:

  geth-bootnode:
    hostname: geth-bootnode
    env_file:
      - .env
    image: geth-client-clique
    build:
      context: .
      args:
        - CHAIN_ID=${CHAIN_ID}
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
        - ACCOUNT_BALANCE=${ACCOUNT_BALANCE}
        - GAS_LIMIT=${GAS_LIMIT}
    command:
      --nodekeyhex="b0ac22adcad37213c7c565810a50f1772291e7b0ce53fb73e7ec2a3c75bc13b5"
      --ipcdisable
      --networkid=${CHAIN_ID}
      --netrestrict="172.16.1.0/24"
    networks:
      priv-eth-net-poa:

  geth-rpc-endpoint:
    hostname: geth-rpc-endpoint
    env_file:
      - .env
    image: geth-client-clique
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,personal"
      --http.corsdomain="*"
      --networkid=${CHAIN_ID}
      --netrestrict="172.16.1.0/24"
    ports:
      - "8545:8545"
    networks:
      priv-eth-net-poa:

  geth-miner1:
    hostname: geth-miner1
    env_file:
      - .env
    image: geth-client-clique
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --allow-insecure-unlock
      --mine
      --miner.threads=1
      --networkid=${CHAIN_ID}
      --netrestrict="172.16.1.0/24"
    networks:
      priv-eth-net-poa:

networks:
  priv-eth-net-poa:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.1.0/24
